apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-app
  labels:
    app: recipe-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recipe-app
  template:
    metadata:
      labels:
        app: recipe-app
    spec:
      containers:
        - name: recipe-app
          #image: recipe-app:latest
          image: tubarecipeacr.azurecr.io/recipe-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"